### ISSUE TITLE
Always sending last item context (v3)

### ISSUE THREAD

**Issue by DevVanilli** [minwork/react#11]
When rendering a list of buttons (using array.map with each button having different context), then no matter which button to press and hold, the context is always last element's context.

It was okay with v2.0.4.

**Comment by minwork** [comment]
Hey @DevVanilli should be fixed in `v3.1.4-alpha.1`

**Comment by DevVanilli** [comment]
Yes, it is! Thanks!

**Comment by minwork** [comment]
Fix included in [v3.1.4 release](https://github.com/minwork/react/releases/tag/use-long-press-v3.1.4)
