### ISSUE TITLE
package.json should have the types property inside 'exports' field so that TS types can be correctly imported

### ISSUE THREAD

**Issue by iampava** [minwork/react#18]
This is the error I get when trying to import the `use-long-press` hook: 

```
import { useLongPress } from "use-long-press";
```

> Could not find a declaration file for module 'use-long-press'. '/Users/[...]/node_modules/use-long-press/index.mjs' implicitly has an 'any' type. There are types at '/Users/[...]/node_modules/use-long-press/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'use-long-press' library may need to update its package.json or typings.ts(7016)

**Comment by icewind7030** [comment]
Ran into the same problem here.

**Comment by minwork** [comment]
@iampava Could you verify it works properly on `use-long-press@3.2.0-alpha.1`?

**Comment by icewind7030** [comment]
I just installed `3.2.0-alpha.1` ，the ts warning is gone and I got the right type assistant！ @minwork 
<img width="955" alt="image" src="https://github.com/minwork/react/assets/7500226/7df1d66d-cc73-4078-afe1-54a097f2bc36">

**Comment by iampava** [comment]
Looks good on my side too 🙌

**Comment by minwork** [comment]
Released in [v3.2.0](https://github.com/minwork/react/releases/tag/use-long-press-v3.2.0)
