### ISSUE TITLE
how to cancel a long press after it has started using custom logic?

### ISSUE THREAD

**Issue by 55Cancri** [minwork/react#40]
I want to cancel a longpress if it has a certain parent.

I tried doing like:

 longPressOpts={{
        onStart: (e) => {
          const el = e.target as HTMLDivElement;
          if (el.closest(".sp-wrapper")) {
            console.log("stopping longpress");
            e.preventDefault();
            e.stopPropagation();
          }
        },
      }}
      
which I thought should cancel the long press if the click was instead a parent with class .sp-wrapper, but it does not. Can a long press be canceled?

**Comment by minwork** [comment]
Hey @55Cancri you can use [filter events](https://minwork.gitbook.io/long-press-hook/advanced/options/react-events/filtering-events) option to achieve this behaviour - just return `false` if event target has certain parent.
