### ISSUE TITLE
did not detect when mouse move out

### ISSUE THREAD

**Issue by rharkor** [minwork/react#7]
I use use-long-press in my react app to enter in edit mode in a card. It work fine but when the use enter the long press on the card and release it out of it your library still count it as a long press, even if the press was shorter than the threshold

This is my card:
```tsx
<div
      className="w-[300px] h-[200px] relative"
      {...bind()}
      style={{
        animationName: selected ? "shake" : "none",
        animationDuration: "0.5s",
        animationTimingFunction: "ease-in-out",
      }}
    >
      Content here
      <EditItemOverlay
        item={item}
        selected={selected}
        setSelected={setSelected}
        editItem={editItem}
      />
    </div>
```

**Comment by minwork** [comment]
Hey @rharkor, there was a change in behaviour to detect long press release even if it was outside of element (I will add an option to automatically cancel long press outside element if desired) but it shouldn't happen if the time was shorter than threshold (I even wrote a test to check this case). 

If you want to cancel long press when moving outside of an element you can use `cancelOnMovement` as a temporary solution until I will add an option mentioned above.

**Comment by minwork** [comment]
I've just published `use-long-press@3.1.0-alpha.1` so you can try it with option `cancelOutsideElement: true` to see if that's the result you are expecting.

**Comment by minwork** [comment]
Also I've noticed behaviour you've described regarding triggering long press even if threshold time didn't elapsed, I will address that as soon as possible.

**Comment by rharkor** [comment]
Hi @minwork the `cancelOutsideElement` worked perfeclty thak's for your fast answer! :heart:

**Comment by minwork** [comment]
@rharkor FYI `use-long-press@3.1.0` is out now
